#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d TERM WEB CODE MISC EDIT CHAT DISCORD MUSIC

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
feh --bg-scale ~/wallpaper/gruvbox-theme/my-current-background.jpg
ibus-daemon -drx &
polybar mybar &
picom &
